version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
       - notes-mysql-data:/var/lib/mysql
       - ./db.sql:/db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: Notes
  server:
    image: python:3.9-alpine
    command: >
      sh -c "python3 -m pip install --no-cache -r requirements.txt &&
             python3 src/server/server.py"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      SERVER_HOST: server
    ports:
      - 3929:3929
  client:
    image: python:3.9-alpine
    command: >
      sh -c "apk add vim &&
             python3 -m pip install --no-cache -r requirements.txt &&
             tail -f /dev/null"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      SERVER_HOST: server

volumes:
  notes-mysql-data:
